

A lot of revolutionary ideas and the results we got from them were computer science and the machine called the computer. Any science in this world that we build borrows axioms/rules/structures from other sciences. We also describe rules on how, where, and when to use the borrowed axioms/rules/structures. Mathematical axioms are all based on logic, physics is based on mathematics, and many more such examples are present. Computer science is a science that does borrow axioms and rules from other sciences, but also performs operations of the same sciences. Now I am going to talk about the key ideas that gave birth to computer science.

The biggest idea, according to me, is the idea of representation. Representation of information using a standard system. Let us say we borrow from mathematics just two numbers (0 and 1) and represent any letter, any number, any character, any story, any sentence, any logical symbol, or object using combinations of two numbers. Follow these two simple steps, number one being: borrow any $n$ number of objects from any domain, and then represent information from any domain using combinations of those $n$ objects from any given domain. You can even represent information from that domain using combinations of those $n$ objects from the same domain. You can even form multiple encodings, meaning that you use different sets of combination lengths and different mappings of the $n$ objects to represent all information (but using those $n$ objects that are borrowed). In one encoding you must fix the size of the combinations and the information you are going to represent (domain of that encoding) i.e fix the number of objects/information one encoding can distinguish. The objects and information one encoding can distinguish can be called a domain in information theory. When using the representation, we must know the what encoding is being used. 

In this idea, we may use the same combination of those $n$ objects to represent information from two different domains/sciences. Two different encodings can have the same combination pointing to different objects. The same object may have two different representations because we can actually create multiple encodings (different combinations formed for objects), but two different objects can't have the same representation in the same encoding (because we need to distinguish items). A single object may have multiple representations. If we had, however, decided to create unique combinations for every single piece of information from every single domain, we would have had to create a lot of combinations.

It is usually represented by $X$ $\rightarrow$ $(01), (abc), (78910)$. This means the information $X$ is being represented by combinations of $01$, or maybe $abc$, or maybe $78910$. Let's say we pick up the objects $a$ and $b$ to represent information. Now let's represent the alphabets using $a$ and $b$.

$X$ $\rightarrow$ combinations of $(a,b)$

We now choose the max number of repetitions allowed, or length per se, for every domain we are trying to represent. Let us here choose it to be 5. Then $a$ $\rightarrow$ $aaaaa$, $b$ $\rightarrow$ $bbbbb$, $c$ $\rightarrow$ $ababa$, and so on. We just formed an encoding here. We picked any $n$, in this case $n=2$ objects, and then used combinations of those objects to represent the alphabet. Now, for any given domain and a single encoding, we want every piece of information to have a unique combination in that encoding. If we choose $n$ objects and $L$ as the length, then the number of pieces of information we can distinguish equals the number of combinations ($N$).

$N$ $=$ $n^{L}$, which implies $\log_n(N)$ $=$ $L$. According to information theory, we keep $n$ $=$ $2$, so naturally $\log_2(N)$ $=$ $L$ becomes our equation. So, the minimum length to distinguish $N$ pieces of information. Note: There can be multiple domains inside a science, and $\log_2(N)$ $=$ $L$ is for a single encoding for any domain.

Now the next big idea is to represent these combinations physically. Now, any $n$ objects you choose, we can describe those combinations physically. If we choose $0$ and $1$ as our objects, then we can represent information using electronic circuits (where high voltage means 0 and low voltage means 1), so yet again we make another encoding of physical phenomena into this information theory system of ours. Circuits may not be the physical encoding. It could have been anything. Here is the overall structure I am observing. There are different sciences like mathematics, physics, and logic that borrow rules/structures/axioms from each other. We choose what to inherit and what not to inherit, and when to use it and when not to use it in any domain or structure. For our information theory, we borrow, of course, the objects from other domains to represent information, and in some cases, we also may borrow other axioms/rules from other domains to actually create rules for the encodings. For the physical interpretation of information theory, we take axioms from physics.

Now, when we talk about computers, they use circuits to store information. Storage units with either high voltage (1) or low voltage (0). The following fact must be clear: To represent information, computer science uses $0$ and $1$. Computer science borrows from both the physical and abstract interpretations of information theory.

## How do computers store information? (physical and abstract interpretation of information theory)

A long row of electronic storage units with high voltage representing $1$ and low voltage representing $0$. A series of storage units placed adjacent to each other would be considered combinations of $0$ and $1$. Now, one storage unit/partial information stored in one electronic storage unit is called a bit. $8$ bits make $1$ byte. You will understand the significance of a byte later when we understand the science of computation. Now, how are we representing information from different domains in computer science? We are borrowing from information theory, but how? What are the details of the representation of many of the domains?

### Integers

Modern computers use 8 bits to represent a number $x$, where $0$ $<=$ $x$ $<=$ $255$. This is information theory. You had 256 distinct objects to distinguish and had two objects used for representation. According to information theory: $\log_n(N)$ $=$ $L$, which implies $\log_2(256)$ $=$ $L$.

So $L$ $=$ $8$, and that is why we use 8 bits (or 1 byte). Integers from $0$ $<=$ $x$ < $65,535$ are represented using 16 bits (or 2 bytes). Now we can think of many other architectures, and each of them would actually lead to a new type of computer. Then there are integers that use 32 bits, and finally integers using 64 bits to represent $x$, such that

$0$ $<=$ $x$ $<=$ $18,446,744,073,709,551,615$.

The domain here is the positive integers, and we just showed you the encoding that computers generally use. You can now imagine at least the abstract interpretation of information theory in computer science related to integers. What about negative integers? How do we represent them? We simply use a different encoding. It is important to understand that a domain and objects under that domain may be represented using different encodings, so the same integer can have two different representations in multiple encodings. If you notice above, when we wanted to distinguish 256 positive integers, we used 8 bits and then 16 bits and so on. We were actually forming different encodings to represent positive integers.

We will talk about characters, images, sound, and numbers with decimals in further sections in detail. How does a computer represent them, and what are the common encodings used?

Before ending this section, we have an important question in front of us. For the physical interpretation of information theory in computer science, we do use electric storage units. For integers, we just understood the different encodings. How are they stored in the long series of electric storage units? Well, a simple rule is followed: A series of storage units (combinations of 1 and 0) may represent different objects in different encodings or the same object in different encodings.
